version: '3'
services:
  webserver:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - project-network
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - project-network
networks:
  project-network:
